"""
RLM sandbox server — preamble injected into the Monty sandbox before user code.

Provides the Python-side API for the RLM (Repeated LLM → Monty) loop.
All functions resolve via HostTool dispatch (implemented in TypeScript) and
do NOT have Python-side implementations — they exist as type-checker stubs
only (generated by ToolRegistry.renderTypeStubs()).

Available to user code:
  - context: str          — The loaded file/context data (monty input)
  - llm_query(prompt)     — Ask the sub-LLM a question, returns its response
  - rlm_query(query, ...) — Spawn a nested RLM loop, returns its final answer
  - SUBMIT(answer)        — Signal completion with the final answer

Plus all Pi bridge tools: read, grep, find, ls, bash, edit, write
Plus builtins: read_file, list_files, http_get
"""

# ═══════════════════════════════════════════════════════════════════
# Context
# ═══════════════════════════════════════════════════════════════════

# `context` is injected as a monty input variable. It contains the
# file contents or raw data the user provided via --path or --data.
# Type annotation exists in the type-check prefix (generated by
# ToolRegistry). At runtime, monty binds it before execution starts.

# ═══════════════════════════════════════════════════════════════════
# Host-tool API (resolved by ToolRegistry → MontyNameLookup dispatch)
# ═══════════════════════════════════════════════════════════════════

# The functions below are NOT defined at the Python level. They are
# HostTools registered in the TypeScript ToolRegistry. When user code
# calls them, monty pauses at MontyNameLookup, and the sandbox runner
# dispatches through the tool's execute() method.
#
# Type stubs (for monty's type checker) are generated by
# registry.renderTypeStubs() and passed as typeCheckPrefixCode.

# llm_query(prompt: str) -> str
#     Ask the sub-LLM a question. Blocks until the LLM responds.
#     Use for: semantic reasoning, summarization, open-ended analysis.
#     Avoid for: counting, filtering, regex — do those in Python directly.

# rlm_query(query: str, context: str | None = None) -> str
#     Spawn a nested RLM loop to investigate a sub-question.
#     The nested loop gets its own sandbox and fresh LLM sessions.
#     At maxDepth (default 1), downgrades to llm_query() internally.
#     Use for: deep multi-step sub-investigations that need code execution.

# SUBMIT(answer: str) -> None
#     Signal completion and return the final answer to the RLM loop.
#     Raises SystemExit internally (caught by the RLM loop runner).
#     The answer is recorded in ToolCallTrace for the RLM loop to extract.
#     MUST be called exactly once at the end of a successful investigation.
#     After SUBMIT, no further code executes in this run.

# ═══════════════════════════════════════════════════════════════════
# Utility helpers
# ═══════════════════════════════════════════════════════════════════

def context_preview(max_chars: int = 500) -> str:
    """Return a truncated preview of the context for quick inspection."""
    if not context:
        return "(empty context)"
    if len(context) <= max_chars:
        return context
    half = max_chars // 2
    return context[:half] + "\n...\n" + context[-half:]


def context_lines() -> list[str]:
    """Return context split into lines. Convenience for line-based analysis."""
    if not context:
        return []
    return context.split("\n")


def context_length() -> int:
    """Return the total character length of the context."""
    return len(context) if context else 0


def context_summary() -> str:
    """Return a one-line summary: file type, size, line count."""
    if not context:
        return "context: empty"
    lines = context.split("\n")
    return f"context: {len(context)} chars, {len(lines)} lines, first line: {lines[0][:80]!r}"
