// Shared types for repl-simple Pi extension

/** Parameter definition for a HostTool */
export interface HostToolParam {
  name: string;
  type: "str" | "bool" | "int" | "float";
  description: string;
  optional?: boolean;
}

/** A host-side tool available to sandboxed Python code */
export interface HostTool {
  name: string;
  description: string;
  params: HostToolParam[];
  returns: "str" | "void";
  execute(args: Record<string, unknown>): string | Promise<string>;
  requiresApproval?: boolean;
}

/** Approval request from a gated tool call */
export interface ApprovalRequest {
  tool: string;
  args: unknown[];
  kwargs: Record<string, unknown>;
  description: string;
}

/** Approval decision: true = approved, false = denied, 'suspend' = pause for later resume */
export type ApprovalDecision = boolean | "suspend";

/** Resource limits for a sandbox run */
export interface RunLimits {
  maxDurationSecs: number;
  maxMemory?: number;
}

/** Runtime options for a sandbox execution */
export interface RunOptions {
  inputs?: Record<string, string>;
  mount?: Record<string, string>;
  signal?: AbortSignal;
  onPrint?: (text: string) => void;
  onApproval?: (request: ApprovalRequest) => ApprovalDecision | Promise<ApprovalDecision>;
  /** Byte ceiling on `stdout`. Default 32 KiB. */
  maxStdoutBytes?: number;
  /** Byte ceiling on `output`. Default 16 KiB. */
  maxOutputBytes?: number;
  scriptName?: string;
  limits?: RunLimits;
}

/** Trace of a single host-tool call during execution */
export interface ToolCallTrace {
  tool: string;
  args: unknown[];
  kwargs: Record<string, unknown>;
  durationMs: number;
  ok: boolean;
  error?: string;
  approved?: boolean;
}

/** Kinds of run errors */
export type RunErrorKind = "syntax" | "typing" | "runtime" | "aborted";

/** Successful run result */
export interface RunOk {
  status: "ok";
  output: string;
  /** True when `output` was elided to fit `maxOutputBytes`. */
  outputTruncated: boolean;
  stdout: string;
  stdoutTruncated: boolean;
  calls: ToolCallTrace[];
}

/** Errored run result */
export interface RunError {
  status: "error";
  error: string;
  errorKind: RunErrorKind;
  stdout: string;
  stdoutTruncated: boolean;
  calls: ToolCallTrace[];
}

/** Suspended run result (waiting for approval) */
export interface RunSuspended {
  status: "suspended";
  suspendedCall: ApprovalRequest;
  /** Serialized MontySnapshot — pass to resumeSuspended() to continue. */
  snapshot: Buffer;
  stdout: string;
  stdoutTruncated: boolean;
  calls: ToolCallTrace[];
}

/** Discriminated union of run outcomes */
export type RunResult = RunOk | RunError | RunSuspended;

// ── RLM types ────────────────────────────────────────────────────

import type { ToolRegistry } from "./registry.js";

/**
 * LLM client for generating Python code in RLM loops.
 *
 * Injected by the caller — repl-simple has no LLM dependency of its own.
 * Tests use a mock that returns canned responses from an array.
 */
export interface LlmClient {
  query(
    systemPrompt: string,
    messages: Array<{ role: "user" | "assistant"; content: string }>,
  ): Promise<string>;
}

/** A single iteration of the RLM loop. */
export interface RlmIteration {
  /** Index (0-based). */
  index: number;
  /** Python code generated by the LLM for this iteration. */
  code: string;
  /** Result of sandbox execution. */
  result: RunResult;
  /** Raw LLM response (before code extraction). */
  llmResponse: string;
}

/** RLM loop options. */
export interface RlmOptions {
  /** LLM client for code generation. REQUIRED. */
  llmClient: LlmClient;
  /** Tool registry for the sandbox (must include RLM tools: llm_query, rlm_query, SUBMIT). */
  registry: ToolRegistry;
  /** Python preamble injected before user code (e.g. repl_server.py). */
  preamble?: string;
  /** System prompt for the LLM. Defaults to DEFAULT_RLM_SYSTEM_PROMPT. */
  systemPrompt?: string;
  /** Max RLM iterations before giving up. Default: 10. */
  maxIterations?: number;
  /** Abort signal — checked between iterations. */
  signal?: AbortSignal;
  /** Callback invoked after each iteration completes. */
  onIteration?: (iteration: RlmIteration) => void;
  /** Inputs passed to each sandbox run (e.g. { context: "..." }). */
  inputs?: Record<string, string>;
  /** Sandbox RunOptions propagated to each sandbox run. */
  runOptions?: RunOptions;
}

/** RLM loop result. */
export interface RlmResult {
  /** "ok" when SUBMIT was called, "max_iterations" when loop exhausted. */
  status: "ok" | "max_iterations";
  /** The answer string (from SUBMIT, or best-effort extraction). */
  answer: string;
  /** All iterations executed. */
  iterations: RlmIteration[];
}

/**
 * Error thrown by a host tool that should surface as a Python exception
 * in the sandbox.
 *
 * The `pythonType` property maps to the Python exception class name
 * (e.g. "TypeError", "PermissionError", "RuntimeError", "_SubmitSignal").
 */
export class HostToolError extends Error {
  pythonType: string;

  constructor(pythonType: string, message: string) {
    super(message);
    this.name = "HostToolError";
    this.pythonType = pythonType;
  }
}
